# Generated by Django 3.2.18 on 2023-03-03 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20230303_1625"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("salary", models.CharField(max_length=50)),
                ("skill_requirements", models.CharField(max_length=255)),
                ("openings", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=100)),
                ("posted_on", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Part-Time", "Part-Time"),
                            ("Full-Time", "Full-Time"),
                        ],
                        max_length=155,
                    ),
                ),
                ("apply_by", models.DateField()),
                ("start_date", models.DateField()),
                (
                    "applicants",
                    models.ManyToManyField(
                        limit_choices_to={"user_type": "is_normal"},
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "is_organisation"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
