# Generated by Django 3.2.18 on 2023-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20230303_2223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
