# Generated by Django 3.2.18 on 2023-03-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_auto_20230304_0422"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                default=" faknkdjsfnkadfjnsjdljslkj sjdf lkkjdfl", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_dob",
            field=models.DateField(null=True),
        ),
    ]
